class SophosAPIType():
    IPHOST = "IPHost"
    CERTIFICATE = "Certificate"
    IPHOSTGROUP = "IPHostGroup"
    SERVICES = "Services"
    SERVICEGROUP = "ServiceGroup"
    ZONE = "Zone"
    VLAN = "VLAN"
    INTERFACE = "Interface"
    FIREWALLRULEGROUP = "FirewallRuleGroup"
    FIREWALLRULE = "FirewallRule"
